### PR TITLE
Update hookOnCalculator.ts

### PR DESCRIPTION
**Pull request by dangell7**
Add NFTOKEN Transactions

- [x] NFTokenMint
- [x] NFTokenBurn
- [x] NFTokenCreateOffer
- [x] NFTokenCancelOffer
- [x] NFTokenAcceptOffer

### CODE REVIEW

**Review by vbar — CHANGES_REQUESTED** [review]
Well, the new transactions cannot be run:
createoffer

But even ignoring the format errors, I'm skeptical about Hooks testnet support for NFT transactions - I'd recommend testing (against hooks-testnet-v2.xrpl-labs.com) first, and take the problems to https://github.com/XRPL-Labs/xrpld-hooks ...

**Comment by dangell7** [comment]
> Well, the new transactions cannot be run: createoffer
> 
> But even ignoring the format errors, I'm skeptical about Hooks testnet support for NFT transactions - I'd recommend testing (against hooks-testnet-v2.xrpl-labs.com) first, and take the problems to https://github.com/XRPL-Labs/xrpld-hooks ...

I thought the ide was running the hooks testnet v2?

Either way I will debug this.

**Comment by dangell7** [comment]
@vbar can you provide me with some env credentials to connect to the api? I got the client to build but the api is taking forever...

**Comment by dangell7** [comment]
@vbar

I have found the issue with the builder. In the "Test" tab when choosing the NFTokenCreateOffer the following json is what is created. However, the field is not TokenID, its NFTokenID. 

<img width="1512" alt="Screen Shot 2022-07-13 at 12 35 55 PM" src="https://user-images.githubusercontent.com/25502424/178785632-579c57f5-746c-4ab5-b11d-20d01423fbcd.png"

**Pull request closed without merging**
