### PR TITLE
Testnet v3.

### PR DESCRIPTION
**Pull request by muzam1l**
- [x] `NetworkID` for the network taken from `NEXT_PUBLIC_NETWORK_ID` and falls back to `xrpl-client` provided value.
- [x] Xrpl packages updated to latest version.
- [x] `ripple-binary-codec` definitions patch updated.
- [x] `HookOn` logic updated.
- [x] Implement any new transactions.

### CODE REVIEW

**Review by vbar — COMMENTED** [review]
Looks fine, as far as it goes, but shouldn't the custom JavaScript in examples (firewall, notary & peggy) also be updated to use wss://hooks-testnet-v3.xrpl-labs.com ? Coming to think of it, the examples probably shouldn't hard-code the URL in the first place, but take it from IDE, like another parameter - but I suppose that can wait...

**Comment by muzam1l** [comment]
Yeah updated the JS files now. We will have have the necessary URL's available in js env available later.

**Comment by vbar** [comment]
> Yeah updated the JS files now. We will have have the necessary URL's available in js env available later.

Err, yes, they're updated, but now they fail, with `telREQUIRES_NETWORK_ID`... Probably the scripts need some other change as well?

**Comment by muzam1l** [comment]
Yeah, it needs `NetworkID: "21338"` in transactions, I updated the gist's so it's there now. But, it still won't work cuz it also needs the modified ripple codec library! In ide, we just patch the library on postinstall, but here we import the modules from `esm.sh` with no build step. So that is the thing 😅.

**Comment by vbar** [comment]
> Yeah, it needs `NetworkID: "21338"` in transactions, I updated the gist's so it's there now. But, it still won't work cuz it also needs the modified ripple codec library! In ide, we just patch the library on postinstall, but here we import the modules from `esm.sh` with no build step. So that is the thing sweat_smile.

Well, if we need a released version of ripple codec to support the examples in v3 testnet, I think that's for Richard - he probably knows who's maintaining that...

**Comment by muzam1l** [comment]
Yeah, they probably need to mantain the fork of it themselves!

**Review by vbar — CHANGES_REQUESTED** [review]
Installing hooks works, but trying to delete a hook ends with "Transactions submitted to this node/network must include a correct NetworkID field." - apparently it should be added in some more places...

**Review by vbar — APPROVED** [review]

**Pull request merged**
