### PR TITLE
Add owner field to NFTokenCreateOffer UI.

### LINKED ISSUE #292: Hooks Builder cannot create NFT buy offer
without formatting it directly in JSON, because the transaction GUI doesn't display the `Owner` field:

nftcreate

(see also https://xrpl.org/nftokencreateoffer.html). Ideally the field should show only if the `tfSellNFToken` flag is not set, but I don't think there's any mechanism to change fields allowed for a specific transaction type dynamically, and not sure it's worth implementing...

### PR DESCRIPTION
**Pull request by muzam1l**
Fixes #292.

### CODE REVIEW

**Comment by muzam1l** [comment]
But it is the account of the owner you are buying NFT from. Agreed in testnet you have arbitrary faucet accounts, but you wouldn't have an owner's account imported (access to secrets) in a 'real world' scenario?

**Comment by vbar** [comment]
> But it is the account of the owner you are buying NFT from. Agreed in testnet you have arbitrary faucet accounts, but you wouldn't have an owner's account imported (access to secrets) in a 'real world' scenario?

Yes, but in a "real-world" scenario, you wouldn't have the secret of a Destination account you're sending payments to either... I think the GUI is meant for testing, where I do want to control all accounts participating in the test transaction - admittedly there might be special cases where the tester wants to use an account they don't have a secret of, but that should be handled the same for all account fields, and actually already is, by editing the transaction in JSON...

**Comment by muzam1l** [comment]
Yeah maybe. There are many fields which can be of type Account. We currently have hardcoded state management/json-mode interpolation for `Account` and `Destination`. Do we want to implement generic Account type, which can be enabled for any field? I don't know if thats worth the effort right now?

**Comment by vbar** [comment]
> Yeah maybe. There are many fields which can be of type Account. We currently have hardcoded state management/json-mode interpolation for `Account` and `Destination`. Do we want to implement generic Account type, which can be enabled for any field? I don't know if thats worth the effort right now?

Not that many fields of type Account; apart from Account and Destination, I see only Owner and Issuer - so I don't think a generic Account type is that important... I'd even say other types, e.g. Amount, should be implemented first... :-)

**Comment by vbar** [comment]
> Not that many fields of type Account; apart from Account and Destination, I see only Owner and Issuer

OK, plus some nested fields (including Issuer in Amount) - but those never have GUI, and probably can wait for it...

**Comment by vbar** [comment]
This apparently isn't merged?

nft

**Comment by muzam1l** [comment]
Sorry to mention, Superseded by #296.

**Pull request closed without merging**
