### PR TITLE
Update tx state accounts on delete account.

### LINKED ISSUE #206: Account removal should reset test transaction
test

The test transaction above looks valid but isn't: Alice account was replaced after selecting the field. Builder shouldn't get into a state where "Alice" means different accounts on the same page (some of which it can no longer find), and the easiest way to prevent it is probably by resetting the test transaction whenever an account is deleted.

### PR DESCRIPTION
**Pull request by muzam1l**
Fixes #206

### CODE REVIEW

**Review by vbar — CHANGES_REQUESTED** [review]
Well, deleting the account(s) does change them in the test transaction, but it changes them to the raw account ID, which isn't handled by the rest of IDE:
unknown

(the above is for fee estimate; sending the transaction fails as well). I think it would be better to just reset the account value to empty, making it clear the transaction is invalid because it's missing required field(s)...

**Comment by muzam1l** [comment]
So the idea behind this was not to change the user's state unexpectedly. It also works well if you are in json mode and not have your json changed while you delete account (json restructures upon saving)!. We need account to be imported first to use it (not `Destination` though), and that error I guess gives you pretty clear indication to do that!?

**Comment by vbar** [comment]
> So the idea behind this was not to change the user's state unexpectedly. It also works well if you are in json mode and not have your json changed while you delete account (json restructures upon saving)!. We need account to be imported first to use it (not `Destination` though), and that error I guess gives you pretty clear indication to do that!?

Well, I think it's better to change the state to an already known one than to keep it fixed while extending presentation and changing behavior (i.e. making the transaction invalid)... I think optionally using raw accounts could work, but I'm not sure it's worth the trouble implementing - even the JSON view says the raw account is invalid after it's deleted... But I don't actually have a strong preference - @valstu ? @jonijuup  ?

**Comment by muzam1l** [comment]
Ok, turns changing state is lot more hectic if user is in json mode, imagine Dirty/unsaved editors, where you can't parse/determine the latest state to change it by one field. I think we should go for current implementation for now as it gives clear indication for user in toast message and also user kinda knows that if account was deleted, it can't be used in transaction anymore and should be changed!

**Comment by vbar** [comment]
> I think we should go for current implementation for now

Well OK...

> user kinda knows that if account was deleted, it can't be used in transaction anymore and should be changed!

Although I'm a bit skeptical about this - but I suppose we can wait for the bug reports...

**Review by vbar — APPROVED** [review]

**Pull request merged**
