### PR TITLE
Prettier config!

### PR DESCRIPTION
**Pull request by muzam1l**
~~Only config is added, no formatting done, to focus on config options for now.~~

Options not in config are assumed prettier defaults, which should be consistent and stable.

### CODE REVIEW

**Review by valstu — APPROVED** [review]
Fine with these but personally I would prefer using semicolons for readability reason this is just something i prefer.

**Comment by muzam1l** [comment]
So dropped the bomb `prettier --write .` on all files! Not sure if we want this massive pr in one go, but is all just automatic formatting so maybe good to go??

**Comment by valstu** [comment]
I think we should be ok 🤔 at least the preview seems to be working ok and build passes.

**Review by valstu — APPROVED** [review]

**Comment by valstu** [comment]
Just need to pull latest from main

**Pull request merged**
