### PR TITLE
Transaction amount UI.

### PR DESCRIPTION
**Pull request by muzam1l**

### CODE REVIEW

**Review by vbar — CHANGES_REQUESTED** [review]
Well, it looks nice, but why does it change the field name in OfferCreate (from TakerPays to Amount)? TakerGets should get the option of specifying tokens too... Also, some input validation, e.g. that the currency must have 3 characters (which are not "XRP"), the value must be positive etc. as documented would be nice...

**Comment by muzam1l** [comment]
> but why does it change the field name in OfferCreate (from TakerPays to Amount)?

OfferCreate transaction meta seems wrong already, so will update that accordingly.

**Comment by vbar** [comment]
> > that the currency must have 3 characters.
> 
> Well, Currency can also be a hexadecimal string. https://xrpl.org/currency-formats.html#nonstandard-currency-codes

Well, yes, if you want to have another dropdown there there to select the format - but isn't the GUI getting rather complicated?

**Comment by muzam1l** [comment]
> > > that the currency must have 3 characters.
> > 
> > 
> > Well, Currency can also be a hexadecimal string. https://xrpl.org/currency-formats.html#nonstandard-currency-codes
> 
> Well, yes, if you want to have another dropdown there there to select the format - but isn't the GUI getting rather complicated?

Well, we are not doing any formatting on the Currency field. Users have to enter the correct hexadecimal currency code if they wish to use that.

**Comment by muzam1l** [comment]
> OK, in that case the required length is either 3 for the normal code, or 40 for the quoted hexadecimal - right?

Well, we currently only do structural validation, everywhere not just amounts, and rely on Hooks runtime to do input validation 😅. So yeah, input/pattern validation can be some other pr!

**Comment by vbar** [comment]
> > OK, in that case the required length is either 3 for the normal code, or 40 for the quoted hexadecimal - right?
> 
> Well, we currently only do structural validation, everywhere not just amounts, and rely on xrpl runtime to do input validation sweat_smile. So yeah, input/pattern validation can be some other pr!

But fields that must be filled in are checked to be non-empty - right? For example Payment cannot get a fee estimate until it has specified both sender account and destination - while in this PR, when switching the amount to tokens, the Fee button is enabled but doesn't work...

**Comment by muzam1l** [comment]
>  while in this PR, when switching the amount to tokens, the Fee button is enabled but doesn't work.

That would be a bug. Even if there is some missing validation is UI, the backend is supposed to give all errors correctly!

**Review by vbar — APPROVED** [review]

**Pull request merged**
